### ISSUE TITLE
Seq has value that is not a valid int

### ISSUE THREAD

**Issue by yuzurihaaa** [feedmepos/foodb#13]
I see `ChangeResult` data like this
```
{id: REDACTED, seq: 2-0, deleted: null, changes: [{rev: 1-f61f2eb829ee3be98c6f66a36138bd19}], doc: null}
```
seq "2-0" is not a valid int hence it'll throw error. At this point, it is not throwing `ReplicationException` but `FormatException` from `int.parse(result.seq!)`. 

I also see null seq `{id: REDACTED, seq: null, deleted: null, changes: [{rev: 13-b0d9f77a0cb979172bf3374092ae18b3}], doc: null}` but in the code here, it force unwrap the nullable value `int.parse(result.seq!)`.

_Originally posted by @yuzurihaaa in https://github.com/feedmepos/foodb/issues/11#issuecomment-2091150667_

**Comment by lokingwei** [comment]
my mistaken, the replicate_test.dart is not inside the full testSuite, which missed out the unit test
